language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - TEST_COMMAND=test FEATURES=''
  - TEST_COMMAND=test FEATURES='--features=serde'

matrix:
  include:
    - rust: nightly
      env: TEST_COMMAND=build FEATURES='--no-default-features --features=u32_backend'
    - rust: nightly
      env: TEST_COMMAND=test FEATURES='--features=nightly'

script:
  - cargo $TEST_COMMAND $FEATURES

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
