[package]
name = "ed25519-dalek"
version = "0.2.0"
authors = ["Isis Lovecruft <isis@torproject.org>"]
readme = "README.md"
license = "CC0-1.0"
repository = "https://code.ciph.re/isis/ed25519-dalek"
categories = ["cryptography", "no-std"]
keywords = ["cryptography", "ed25519", "signature", "ECC"]
description = "Fast and efficient ed25519 signing and verification."
exclude = [ ".gitignore", "TESTVECTORS" ]


[dependencies]
arrayref = "0.3.3"
sha2 = "^0.4"

[dependencies.curve25519-dalek]
version = "^0.3"
default-features = false

[dependencies.rand]
optional = true
version = "^0.3"

[dev-dependencies]
rustc-serialize = "0.3"

[features]
default = ["std"]
std = ["rand"]
