[package]
name = "ed25519-dalek"
version = "1.0.0-pre.1"
authors = ["isis lovecruft <isis@patternsinthevoid.net>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/dalek-cryptography/ed25519-dalek"
homepage = "https://dalek.rs"
documentation = "https://docs.rs/ed25519-dalek"
keywords = ["cryptography", "ed25519", "curve25519", "signature", "ECC"]
categories = ["cryptography", "no-std"]
description = "Fast and efficient ed25519 EdDSA key generations, signing, and verification in pure Rust."
exclude = [ ".gitignore", "TESTVECTORS", "res/*" ]

[badges]
travis-ci = { repository = "dalek-cryptography/ed25519-dalek", branch = "master"}

[dependencies.curve25519-dalek]
version = "1"
default-features = false

[dependencies.rand]
version = "0.7"

[dependencies.serde]
version = "^1.0"
optional = true

[dependencies.sha2]
version = "^0.8"
default-features = false

[dependencies.failure]
version = "^0.1.1"
default-features = false

[dependencies.clear_on_drop]
version = "0.2"

[dev-dependencies]
hex = "^0.3"
bincode = "^0.9"
criterion = "0.2"

[[bench]]
name = "ed25519_benchmarks"
harness = false

[features]
default = ["std", "u64_backend"]
std = ["curve25519-dalek/std", "rand/std", "sha2/std"]
alloc = ["curve25519-dalek/alloc"]
nightly = ["curve25519-dalek/nightly", "rand/nightly", "clear_on_drop/nightly"]
asm = ["sha2/asm"]
yolocrypto = ["curve25519-dalek/yolocrypto"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
avx2_backend = ["curve25519-dalek/avx2_backend"]
