[package]
name = "ed25519-dalek"
version = "0.3.2"
authors = ["Isis Lovecruft <isis@torproject.org>"]
readme = "README.md"
license = "CC0-1.0"
repository = "https://github.com/isislovecruft/ed25519-dalek"
homepage = "https://code.ciph.re/isis/ed25519-dalek"
documentation = "https://docs.rs/ed25519-dalek"
keywords = ["cryptography", "ed25519", "curve25519", "signature", "ECC"]
categories = ["cryptography", "no-std"]
description = "Fast and efficient ed25519 signing and verification in pure Rust."
exclude = [ ".gitignore", "TESTVECTORS", "res/*" ]

[badges]
travis-ci = { repository = "isislovecruft/ed25519-dalek", branch = "master"}

[dependencies]
arrayref = "0.3.3"

[dependencies.curve25519-dalek]
version = "^0.9"
default-features = false

[dependencies.rand]
optional = true
version = "^0.3"

[dependencies.digest]
version = "^0.6"

[dependencies.generic-array]
# same version that digest depends on
version = "^0.6"

[dev-dependencies]
rustc-serialize = "0.3"
sha2 = "^0.6"

[features]
default = ["std"]
std = ["rand", "curve25519-dalek/std"]
bench = []
nightly = ["curve25519-dalek/nightly"]
